common:
  includes:
  - RTOS
  - RTOS\FreeRTOS
  - RTOS\FreeRTOS\CMSIS_RTOS
  - RTOS\FreeRTOS\include
  - RTOS\FreeRTOS\portable
  - RTOS\FreeRTOS\portable\BCC
  - RTOS\FreeRTOS\portable\BCC\16BitDOS
  - RTOS\FreeRTOS\portable\BCC\16BitDOS\Flsh186
  - RTOS\FreeRTOS\portable\BCC\16BitDOS\PC
  - RTOS\FreeRTOS\portable\BCC\16BitDOS\common
  - RTOS\FreeRTOS\portable\CCS
  - RTOS\FreeRTOS\portable\CCS\ARM_CM3
  - RTOS\FreeRTOS\portable\CCS\ARM_CM4F
  - RTOS\FreeRTOS\portable\CCS\ARM_Cortex-R4
  - RTOS\FreeRTOS\portable\CCS\MSP430X
  - RTOS\FreeRTOS\portable\CodeWarrior
  - RTOS\FreeRTOS\portable\CodeWarrior\ColdFire_V1
  - RTOS\FreeRTOS\portable\CodeWarrior\ColdFire_V2
  - RTOS\FreeRTOS\portable\CodeWarrior\HCS12
  - RTOS\FreeRTOS\portable\GCC
  - RTOS\FreeRTOS\portable\GCC\ARM7_AT91FR40008
  - RTOS\FreeRTOS\portable\GCC\ARM7_AT91SAM7S
  - RTOS\FreeRTOS\portable\GCC\ARM7_LPC2000
  - RTOS\FreeRTOS\portable\GCC\ARM7_LPC23xx
  - RTOS\FreeRTOS\portable\GCC\ARM_CA53_64_BIT
  - RTOS\FreeRTOS\portable\GCC\ARM_CA9
  - RTOS\FreeRTOS\portable\GCC\ARM_CM0
  - RTOS\FreeRTOS\portable\GCC\ARM_CM3
  - RTOS\FreeRTOS\portable\GCC\ARM_CM3_MPU
  - RTOS\FreeRTOS\portable\GCC\ARM_CM4F
  - RTOS\FreeRTOS\portable\GCC\ARM_CM4_MPU
  - RTOS\FreeRTOS\portable\GCC\ARM_CM7
  - RTOS\FreeRTOS\portable\GCC\ARM_CM7\r0p1
  - RTOS\FreeRTOS\portable\GCC\ARM_CR5
  - RTOS\FreeRTOS\portable\GCC\ARM_CRx_No_GIC
  - RTOS\FreeRTOS\portable\GCC\ATMega323
  - RTOS\FreeRTOS\portable\GCC\AVR32_UC3
  - RTOS\FreeRTOS\portable\GCC\CORTUS_APS3
  - RTOS\FreeRTOS\portable\GCC\ColdFire_V2
  - RTOS\FreeRTOS\portable\GCC\H8S2329
  - RTOS\FreeRTOS\portable\GCC\HCS12
  - RTOS\FreeRTOS\portable\GCC\IA32_flat
  - RTOS\FreeRTOS\portable\GCC\MCF5235
  - RTOS\FreeRTOS\portable\GCC\MSP430F449
  - RTOS\FreeRTOS\portable\GCC\MicroBlaze
  - RTOS\FreeRTOS\portable\GCC\MicroBlazeV8
  - RTOS\FreeRTOS\portable\GCC\MicroBlazeV9
  - RTOS\FreeRTOS\portable\GCC\NiosII
  - RTOS\FreeRTOS\portable\GCC\PPC405_Xilinx
  - RTOS\FreeRTOS\portable\GCC\PPC440_Xilinx
  - RTOS\FreeRTOS\portable\GCC\RL78
  - RTOS\FreeRTOS\portable\GCC\RX100
  - RTOS\FreeRTOS\portable\GCC\RX600
  - RTOS\FreeRTOS\portable\GCC\RX600v2
  - RTOS\FreeRTOS\portable\GCC\STR75x
  - RTOS\FreeRTOS\portable\GCC\TriCore_1782
  - RTOS\FreeRTOS\portable\IAR
  - RTOS\FreeRTOS\portable\IAR\78K0R
  - RTOS\FreeRTOS\portable\IAR\ARM_CA5_No_GIC
  - RTOS\FreeRTOS\portable\IAR\ARM_CA9
  - RTOS\FreeRTOS\portable\IAR\ARM_CM0
  - RTOS\FreeRTOS\portable\IAR\ARM_CM3
  - RTOS\FreeRTOS\portable\IAR\ARM_CM4F
  - RTOS\FreeRTOS\portable\IAR\ARM_CM4F_MPU
  - RTOS\FreeRTOS\portable\IAR\ARM_CM7
  - RTOS\FreeRTOS\portable\IAR\ARM_CM7\r0p1
  - RTOS\FreeRTOS\portable\IAR\ARM_CRx_No_GIC
  - RTOS\FreeRTOS\portable\IAR\ATMega323
  - RTOS\FreeRTOS\portable\IAR\AVR32_UC3
  - RTOS\FreeRTOS\portable\IAR\AtmelSAM7S64
  - RTOS\FreeRTOS\portable\IAR\AtmelSAM9XE
  - RTOS\FreeRTOS\portable\IAR\LPC2000
  - RTOS\FreeRTOS\portable\IAR\MSP430
  - RTOS\FreeRTOS\portable\IAR\MSP430X
  - RTOS\FreeRTOS\portable\IAR\RL78
  - RTOS\FreeRTOS\portable\IAR\RX100
  - RTOS\FreeRTOS\portable\IAR\RX600
  - RTOS\FreeRTOS\portable\IAR\RXv2
  - RTOS\FreeRTOS\portable\IAR\STR71x
  - RTOS\FreeRTOS\portable\IAR\STR75x
  - RTOS\FreeRTOS\portable\IAR\STR91x
  - RTOS\FreeRTOS\portable\IAR\V850ES
  - RTOS\FreeRTOS\portable\MPLAB
  - RTOS\FreeRTOS\portable\MPLAB\PIC18F
  - RTOS\FreeRTOS\portable\MPLAB\PIC24_dsPIC
  - RTOS\FreeRTOS\portable\MPLAB\PIC32MEC14xx
  - RTOS\FreeRTOS\portable\MPLAB\PIC32MX
  - RTOS\FreeRTOS\portable\MPLAB\PIC32MZ
  - RTOS\FreeRTOS\portable\MSVC-MingW
  - RTOS\FreeRTOS\portable\MikroC
  - RTOS\FreeRTOS\portable\MikroC\ARM_CM4F
  - RTOS\FreeRTOS\portable\Paradigm
  - RTOS\FreeRTOS\portable\Paradigm\Tern_EE
  - RTOS\FreeRTOS\portable\Paradigm\Tern_EE\large_untested
  - RTOS\FreeRTOS\portable\Paradigm\Tern_EE\small
  - RTOS\FreeRTOS\portable\RVDS
  - RTOS\FreeRTOS\portable\RVDS\ARM7_LPC21xx
  - RTOS\FreeRTOS\portable\RVDS\ARM_CA9
  - RTOS\FreeRTOS\portable\RVDS\ARM_CM0
  - RTOS\FreeRTOS\portable\RVDS\ARM_CM3
  - RTOS\FreeRTOS\portable\RVDS\ARM_CM4F
  - RTOS\FreeRTOS\portable\RVDS\ARM_CM4_MPU
  - RTOS\FreeRTOS\portable\RVDS\ARM_CM7
  - RTOS\FreeRTOS\portable\RVDS\ARM_CM7\r0p1
  - RTOS\FreeRTOS\portable\Renesas
  - RTOS\FreeRTOS\portable\Renesas\RX100
  - RTOS\FreeRTOS\portable\Renesas\RX200
  - RTOS\FreeRTOS\portable\Renesas\RX600
  - RTOS\FreeRTOS\portable\Renesas\RX600v2
  - RTOS\FreeRTOS\portable\Renesas\SH2A_FPU
  - RTOS\FreeRTOS\portable\Rowley
  - RTOS\FreeRTOS\portable\Rowley\MSP430F449
  - RTOS\FreeRTOS\portable\SDCC
  - RTOS\FreeRTOS\portable\SDCC\Cygnal
  - RTOS\FreeRTOS\portable\Softune
  - RTOS\FreeRTOS\portable\Softune\MB91460
  - RTOS\FreeRTOS\portable\Softune\MB96340
  - RTOS\FreeRTOS\portable\Tasking
  - RTOS\FreeRTOS\portable\Tasking\ARM_CM4F
  - RTOS\FreeRTOS\portable\WizC
  - RTOS\FreeRTOS\portable\WizC\PIC18
  - RTOS\FreeRTOS\portable\oWatcom
  - RTOS\FreeRTOS\portable\oWatcom\16BitDOS
  - RTOS\FreeRTOS\portable\oWatcom\16BitDOS\Flsh186
  - RTOS\FreeRTOS\portable\oWatcom\16BitDOS\PC
  - RTOS\FreeRTOS\portable\oWatcom\16BitDOS\common
  sources:
    RTOS:
    - RTOS\FreeRTOS
    - RTOS\FreeRTOS\CMSIS_RTOS
    - RTOS\FreeRTOS\portable\BCC\16BitDOS\Flsh186
    - RTOS\FreeRTOS\portable\BCC\16BitDOS\PC
    - RTOS\FreeRTOS\portable\BCC\16BitDOS\common
    - RTOS\FreeRTOS\portable\CCS\ARM_CM3
    - RTOS\FreeRTOS\portable\CCS\ARM_CM4F
    - RTOS\FreeRTOS\portable\CCS\ARM_Cortex-R4
    - RTOS\FreeRTOS\portable\CCS\MSP430X
    - RTOS\FreeRTOS\portable\CodeWarrior\ColdFire_V1
    - RTOS\FreeRTOS\portable\CodeWarrior\ColdFire_V2
    - RTOS\FreeRTOS\portable\CodeWarrior\HCS12
    - RTOS\FreeRTOS\portable\Common
    - RTOS\FreeRTOS\portable\GCC\ARM7_AT91FR40008
    - RTOS\FreeRTOS\portable\GCC\ARM7_AT91SAM7S
    - RTOS\FreeRTOS\portable\GCC\ARM7_LPC2000
    - RTOS\FreeRTOS\portable\GCC\ARM7_LPC23xx
    - RTOS\FreeRTOS\portable\GCC\ARM_CA53_64_BIT
    - RTOS\FreeRTOS\portable\GCC\ARM_CA9
    - RTOS\FreeRTOS\portable\GCC\ARM_CM0
    - RTOS\FreeRTOS\portable\GCC\ARM_CM3
    - RTOS\FreeRTOS\portable\GCC\ARM_CM3_MPU
    - RTOS\FreeRTOS\portable\GCC\ARM_CM4F
    - RTOS\FreeRTOS\portable\GCC\ARM_CM4_MPU
    - RTOS\FreeRTOS\portable\GCC\ARM_CM7\r0p1
    - RTOS\FreeRTOS\portable\GCC\ARM_CR5
    - RTOS\FreeRTOS\portable\GCC\ARM_CRx_No_GIC
    - RTOS\FreeRTOS\portable\GCC\ATMega323
    - RTOS\FreeRTOS\portable\GCC\AVR32_UC3
    - RTOS\FreeRTOS\portable\GCC\CORTUS_APS3
    - RTOS\FreeRTOS\portable\GCC\ColdFire_V2
    - RTOS\FreeRTOS\portable\GCC\H8S2329
    - RTOS\FreeRTOS\portable\GCC\HCS12
    - RTOS\FreeRTOS\portable\GCC\IA32_flat
    - RTOS\FreeRTOS\portable\GCC\MCF5235
    - RTOS\FreeRTOS\portable\GCC\MSP430F449
    - RTOS\FreeRTOS\portable\GCC\MicroBlaze
    - RTOS\FreeRTOS\portable\GCC\MicroBlazeV8
    - RTOS\FreeRTOS\portable\GCC\MicroBlazeV9
    - RTOS\FreeRTOS\portable\GCC\NiosII
    - RTOS\FreeRTOS\portable\GCC\PPC405_Xilinx
    - RTOS\FreeRTOS\portable\GCC\PPC440_Xilinx
    - RTOS\FreeRTOS\portable\GCC\RL78
    - RTOS\FreeRTOS\portable\GCC\RX100
    - RTOS\FreeRTOS\portable\GCC\RX600
    - RTOS\FreeRTOS\portable\GCC\RX600v2
    - RTOS\FreeRTOS\portable\GCC\STR75x
    - RTOS\FreeRTOS\portable\GCC\TriCore_1782
    - RTOS\FreeRTOS\portable\IAR\78K0R
    - RTOS\FreeRTOS\portable\IAR\ARM_CA5_No_GIC
    - RTOS\FreeRTOS\portable\IAR\ARM_CA9
    - RTOS\FreeRTOS\portable\IAR\ARM_CM0
    - RTOS\FreeRTOS\portable\IAR\ARM_CM3
    - RTOS\FreeRTOS\portable\IAR\ARM_CM4F
    - RTOS\FreeRTOS\portable\IAR\ARM_CM4F_MPU
    - RTOS\FreeRTOS\portable\IAR\ARM_CM7\r0p1
    - RTOS\FreeRTOS\portable\IAR\ARM_CRx_No_GIC
    - RTOS\FreeRTOS\portable\IAR\ATMega323
    - RTOS\FreeRTOS\portable\IAR\AVR32_UC3
    - RTOS\FreeRTOS\portable\IAR\AtmelSAM7S64
    - RTOS\FreeRTOS\portable\IAR\AtmelSAM9XE
    - RTOS\FreeRTOS\portable\IAR\LPC2000
    - RTOS\FreeRTOS\portable\IAR\MSP430
    - RTOS\FreeRTOS\portable\IAR\MSP430X
    - RTOS\FreeRTOS\portable\IAR\RL78
    - RTOS\FreeRTOS\portable\IAR\RX100
    - RTOS\FreeRTOS\portable\IAR\RX600
    - RTOS\FreeRTOS\portable\IAR\RXv2
    - RTOS\FreeRTOS\portable\IAR\STR71x
    - RTOS\FreeRTOS\portable\IAR\STR75x
    - RTOS\FreeRTOS\portable\IAR\STR91x
    - RTOS\FreeRTOS\portable\IAR\V850ES
    - RTOS\FreeRTOS\portable\MPLAB\PIC18F
    - RTOS\FreeRTOS\portable\MPLAB\PIC24_dsPIC
    - RTOS\FreeRTOS\portable\MPLAB\PIC32MEC14xx
    - RTOS\FreeRTOS\portable\MPLAB\PIC32MX
    - RTOS\FreeRTOS\portable\MPLAB\PIC32MZ
    - RTOS\FreeRTOS\portable\MSVC-MingW
    - RTOS\FreeRTOS\portable\MemMang
    - RTOS\FreeRTOS\portable\MikroC\ARM_CM4F
    - RTOS\FreeRTOS\portable\Paradigm\Tern_EE\large_untested
    - RTOS\FreeRTOS\portable\Paradigm\Tern_EE\small
    - RTOS\FreeRTOS\portable\RVDS\ARM7_LPC21xx
    - RTOS\FreeRTOS\portable\RVDS\ARM_CA9
    - RTOS\FreeRTOS\portable\RVDS\ARM_CM0
    - RTOS\FreeRTOS\portable\RVDS\ARM_CM3
    - RTOS\FreeRTOS\portable\RVDS\ARM_CM4F
    - RTOS\FreeRTOS\portable\RVDS\ARM_CM4_MPU
    - RTOS\FreeRTOS\portable\RVDS\ARM_CM7\r0p1
    - RTOS\FreeRTOS\portable\Renesas\RX100
    - RTOS\FreeRTOS\portable\Renesas\RX200
    - RTOS\FreeRTOS\portable\Renesas\RX600
    - RTOS\FreeRTOS\portable\Renesas\RX600v2
    - RTOS\FreeRTOS\portable\Renesas\SH2A_FPU
    - RTOS\FreeRTOS\portable\Rowley\MSP430F449
    - RTOS\FreeRTOS\portable\SDCC\Cygnal
    - RTOS\FreeRTOS\portable\Softune\MB91460
    - RTOS\FreeRTOS\portable\Softune\MB96340
    - RTOS\FreeRTOS\portable\Tasking\ARM_CM4F
    - RTOS\FreeRTOS\portable\WizC\PIC18
    - RTOS\FreeRTOS\portable\WizC\PIC18\Drivers\Tick
    - RTOS\FreeRTOS\portable\oWatcom\16BitDOS\Flsh186
    - RTOS\FreeRTOS\portable\oWatcom\16BitDOS\PC
    - RTOS\FreeRTOS\portable\oWatcom\16BitDOS\common
  target:
  - cortex-m0
tool_specific: {}
